//! SC-W5-079 – Shared event correlation ids for cross-contract tracing.
//!
//! This module provides a `CorrelationId` type and associated functions for
//! propagating a shared correlation identifier across contract boundaries.
//! Backend consumers use the correlation ID to trace a single workflow (e.g.,
//! an SLA calculation that triggers a payment settlement) across events
//! emitted by multiple contracts.
//!
//! # Design
//!
//! A `CorrelationId` is a `u64` value that is:
//! - Generated by the entry-point contract (usually the SLA calculator)
//! - Passed as an argument to downstream contract calls
//! - Emitted in every event topic of the same logical workflow
//!
//! # Join contract
//!
//! The correlation ID is emitted as `topic[3]` of every correlated event,
//! after the event name / version / context symbols. Backends therefore join
//! the SLA entry event with the downstream settlement/escrow events emitted
//! by other contracts on the same workflow by matching `topic[3]` — the
//! standard Soroban topic-indexing pattern. This join used to be impossible:
//! the ID was generated without mixing in the outage id and was dropped from
//! the topics entirely, so distinct outages in the same ledger collapsed onto
//! one shared id and correlated events carried no actionable id at all
//! (#576). The current layout restores both properties.
//!
//! # Integration
//!
//! The SLA calculator's `calculate_sla` function generates a correlation ID
//! from the outage_id and ledger sequence, then carries it in the `sla_calc`
//! event's `topic[3]` and passes it to downstream calls.
//!
//! Downstream contracts (payment escrow, settlement) accept the correlation
//! ID as a parameter and echo it into their own events' `topic[3]`.

use soroban_sdk::{symbol_short, Env, Symbol, SymbolStr, TryFromVal};

/// Opaque correlation identifier for tracing workflows across contracts.
///
/// A `CorrelationId` is a `u64` that uniquely identifies a logical workflow
/// spanning one or more contract calls.  It is deterministic for a given
/// (outage_id, ledger_sequence) pair so that backends can re-derive it.
pub type CorrelationId = u64;

/// Event topic symbol for the correlation ID in cross-contract events.
pub const CORRELATION_TOPIC: Symbol = symbol_short!("corr_id");

/// Generates a deterministic correlation ID from the outage id and the current
/// ledger sequence.
///
/// Uses a FNV-1a hash over the outage-id symbol bytes mixed with the ledger
/// sequence, so a given (outage_id, ledger_sequence) pair always yields the
/// same ID (backends can re-derive it) while *distinct* outages observed in
/// the same ledger do not collapse onto one shared ID (#576).
///
/// The symbol's UTF-8 bytes are read via [`SymbolStr`], which uses wasm-safe
/// host calls rather than `std`. The ledger sequence is mixed in last, so an
/// identical outage re-reported in a later ledger gets a fresh ID.
pub fn generate_correlation_id(env: &Env, outage_id: &Symbol, ledger_sequence: u32) -> CorrelationId {
    let outage_str: SymbolStr = SymbolStr::try_from_val(env, &outage_id.to_symbol_val())
        .expect("outage id symbol must be well-formed");
    let outage_bytes: &[u8] = outage_str.as_ref();

    // Deterministic hash: FNV-1a over the outage id bytes, then the ledger
    // sequence, so both inputs are folded into the trace id.
    let mut hash: u64 = 0xcbf29ce484222325; // FNV-1a offset basis
    for byte in outage_bytes {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x100000001b3); // FNV-1a prime
    }
    hash ^= (ledger_sequence as u64) << 32 | ledger_sequence as u64;
    hash.wrapping_mul(0x100000001b3)
}

/// Builds the 4-topic tuple for a correlated cross-contract event.
///
/// Topic layout:
///   topic[0] = event name (e.g., "sla_calc")
///   topic[1] = event version ("v1")
///   topic[2] = event-specific context (e.g., severity)
///   topic[3] = correlation id (see the join contract above)
///
/// The correlation id is emitted as `topic[3]` rather than payload-only so
/// backends that match on event topics can join the SLA entry event with
/// downstream settlement events. A zero correlation id indicates a bug in the
/// emitter, not a recoverable state, hence the debug assertion (#576).
pub fn correlation_event_topics(
    event_name: Symbol,
    event_version: Symbol,
    context: Symbol,
    correlation_id: CorrelationId,
) -> (Symbol, Symbol, Symbol, u64) {
    debug_assert_ne!(
        correlation_id, 0,
        "correlation id must be set before topics are built (#576)"
    );
    (event_name, event_version, context, correlation_id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::Env;

    #[test]
    fn test_correlation_id_is_deterministic() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        let id1 = generate_correlation_id(&env, &outage, 42);
        let id2 = generate_correlation_id(&env, &outage, 42);
        assert_eq!(id1, id2);
    }

    #[test]
    fn test_correlation_id_changes_with_ledger_sequence() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        // Different ledger sequences must produce different IDs
        let id_seq1 = generate_correlation_id(&env, &outage, 42);
        let id_seq2 = generate_correlation_id(&env, &outage, 100);
        assert_ne!(id_seq1, id_seq2);
    }

    #[test]
    fn test_correlation_id_is_non_zero() {
        let env = Env::default();
        let id = generate_correlation_id(&env, &Symbol::new(&env, "OUT001"), 1);
        assert_ne!(id, 0, "Correlation ID should not be zero");
    }

    #[test]
    fn test_correlation_id_distinct_ledger_sequences() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        // Verify that different ledger sequences produce distinct outputs
        let id1 = generate_correlation_id(&env, &outage, 1);
        let id2 = generate_correlation_id(&env, &outage, 2);
        let id3 = generate_correlation_id(&env, &outage, 3);
        assert_ne!(id1, id2);
        assert_ne!(id2, id3);
        assert_ne!(id1, id3);
    }

    #[test]
    fn test_correlation_id_changes_with_outage_id() {
        let env = Env::default();
        // Regression for #576: distinct outages observed in the SAME ledger
        // must not collapse onto a single correlation id.
        let outage_a = Symbol::new(&env, "OUT_A");
        let outage_b = Symbol::new(&env, "OUT_B");
        let id_a = generate_correlation_id(&env, &outage_a, 42);
        let id_b = generate_correlation_id(&env, &outage_b, 42);
        assert_ne!(
            id_a, id_b,
            "distinct outages in the same ledger must yield distinct correlation ids (#576)"
        );
    }

    #[test]
    fn test_correlation_event_topics_structure() {
        let topics = correlation_event_topics(
            symbol_short!("sla_calc"),
            symbol_short!("v1"),
            symbol_short!("critical"),
            42,
        );
        assert_eq!(topics.0, symbol_short!("sla_calc"));
        assert_eq!(topics.1, symbol_short!("v1"));
        assert_eq!(topics.2, symbol_short!("critical"));
        assert_eq!(topics.3, 42, "correlation id must be emitted in topic[3] (#576)");
    }

    #[test]
    fn test_correlation_id_long_outage_id() {
        let env = Env::default();
        let long_outage = Symbol::new(&env, "INC_2024_03_15_ABCDEF123456");
        let id = generate_correlation_id(&env, &long_outage, 99);
        assert_ne!(id, 0);
    }

    #[test]
    fn test_correlation_id_empty_symbol_still_hashes() {
        let env = Env::default();
        // Edge case: very short symbol
        let short = Symbol::new(&env, "X");
        let id = generate_correlation_id(&env, &short, 1);
        assert_ne!(id, 0);
    }

    #[test]
    fn test_correlation_topic_has_correct_type() {
        let topics = correlation_event_topics(
            symbol_short!("set_int"),
            symbol_short!("v1"),
            symbol_short!("critical"),
            12345,
        );
        assert_eq!(topics.0, symbol_short!("set_int"));
        assert_eq!(topics.1, symbol_short!("v1"));
        assert_eq!(topics.2, symbol_short!("critical"));
        assert_eq!(topics.3, 12345);
    }

    #[test]
    fn test_correlation_id_joins_sla_and_settlement_topics() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        let corr_id = generate_correlation_id(&env, &outage, 42);
        let sla = correlation_event_topics(
            symbol_short!("sla_calc"),
            symbol_short!("v1"),
            symbol_short!("critical"),
            corr_id,
        );
        let settle = correlation_event_topics(
            symbol_short!("set_int"),
            symbol_short!("v1"),
            symbol_short!("critical"),
            corr_id,
        );
        assert_eq!(sla.3, corr_id);
        assert_eq!(settle.3, corr_id);
        assert_eq!(
            sla.3, settle.3,
            "the same workflow must share the topic[3] join key across contracts (#576)"
        );
    }
}
